export ZSH=$HOME/dotfiles/zsh/oh-my-zsh

# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.

if [[ -n $SSH_CONNECTION ]]; then
  ZSH_THEME="mugimaru-remote" # spaceships
  SPACESHIP_NVM_SHOW=false
  SPACESHIP_VENV_SHOW=false
  SPACESHIP_RUBY_SHOW=false
else
  ZSH_THEME="mugimaru-local"
  SPACESHIP_RUBY_SHOW=true
fi

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

# User configuration
export PATH=$PATH:$HOME/bin

source $ZSH/oh-my-zsh.sh

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='emacs'
fi

# powder
alias prr="powder restart"
alias po="powder open"

# ruby/RoR
alias prspec="bundle exec rake 'parallel:drop[3]' 'parallel:create[3]' 'parallel:migrate[3]' 'parallel:spec[3]'"
alias bprspec="RAILS_ENV=test bin/rake 'parallel:drop[4]' 'parallel:create[4]' 'parallel:migrate[4]' 'parallel:spec[4]'"
alias prspec-ndb="bundle exec rake 'parallel:spec[4]'"
alias bprspec-ndb="RAILS_ENV=test bin/rake 'parallel:spec[4]'"

alias jsonc="json | pygmentize -l json"

alias tmux="tmux -2 attach || tmux -2 new"
z() ssh "$@" -t zsh

source $HOME/dotfiles/zsh/local.zsh.sh
