# zmodload zsh/zprof
export DOTFILES=$HOME/dotfiles

# zsh history
export HISTFILE=~/.zsh_history
export HISTSIZE=10000
export SAVEHIST=10000
export HISTCONTROL=ignoredups
setopt append_history # Don't overwrite, append!
setopt INC_APPEND_HISTORY # Write after each command
setopt hist_expire_dups_first # Expire duplicate entries first when trimming history.
setopt hist_fcntl_lock # use OS file locking
setopt hist_ignore_all_dups # Delete old recorded entry if new entry is a duplicate.
setopt hist_lex_words # better word splitting, but more CPU heavy
setopt hist_reduce_blanks # Remove superfluous blanks before recording entry.
setopt hist_save_no_dups # Don't write duplicate entries in the history file.
setopt share_history # share history between multiple shells
setopt HIST_IGNORE_SPACE # Don't record an entry starting with a space.

# alt + left/right
bindkey "^[[1;3C" forward-word
bindkey "^[[1;3D" backward-word

# zplug: https://github.com/zplug/zplug
#
export ZPLUG_HOME=$DOTFILES/zsh/zplug
# git clone https://github.com/zplug/zplug $ZPLUG_HOME
source $ZPLUG_HOME/init.zsh

zplug "zsh-users/zsh-autosuggestions"
# ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#ff00ff,bg=cyan,bold,underline"

# pure theme
zplug mafredri/zsh-async, from:github
zplug sindresorhus/pure, use:pure.zsh, from:github, as:theme

# Directory listings for zsh with git features
zplug supercrabtree/k

# A Zsh plugin to help remembering those shell aliases and Git aliases you once defined.
zplug djui/alias-tips

if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# zplug load --verbose
zplug load

alias tmux="tmux -2 attach || tmux -2 new"
z() ssh "$@" -t zsh
alias lzd='lazydocker'

source $DOTFILES/zsh/local.zsh.sh

# zprof